CONTRIBUTING.md

add contributing guidelines to repo

docs(CONTRIBUTING): add contributing guidelines

---

CONTRIBUTING.md

this pr adds the `yarn generate` command before running `yarn tauri build` to contributing.md

docs(CONTRIBUTING): manual nuxt generate

---

.github/workflows/release.yml

ci: add debug info statement

---

.github/workflows/release.yml

ci: try to fix rust target matrix

---

.github/workflows/release.yml

ci: try to add apple silicon support

---

.github/workflows/release.yml

ci: try to fix things

---

.github/workflows/release.yml

ci: try to exclude arm builds for win & linux

---

.github/workflows/release.yml

ci: remove rust target from exclude

---

.github/workflows/release.yml

ci: fix toolchain name

---

.github/workflows/release.yml

ci: update release url

---

.github/workflows/release.yml

ci: fix upload url name

---

.github/workflows/release.yml

ci: fix missing .os on ubuntu dependency install

---

.github/workflows/release.yml

New CI changes

---

Dockerfile.arm64
Dockerfile.armv7
src-tauri/tauri.conf.json

Merge additional changes for 0.4.3

---

Dockerfile.arm64
Dockerfile.armv7
components/modal/Kanban.vue

Small fixes for v0.6 release

---

src-tauri/Cargo.lock

chore: update cargo lock

---

.github/workflows/release.yml
src-tauri/src/main.rs

Try fixing linux appimage

---

src-tauri/tauri.conf.json

fix: bump version number in tauri.conf.json

---

app.vue
components/kanban/Card.vue
components/kanban/Column.vue
components/kanban/KanbanDescriptionEditor.vue
components/kanban/TagEdit.vue
components/modal/CardTags.vue
components/modal/EditCard.vue
components/modal/RenameBoard.vue
package.json
pages/kanban/[id].vue
types/kanban-types.d.ts
utils/emitter.ts
yarn.lock

feat: card tags

---

components/modal/Changelog.vue

Added changelog for release v0.7.0

---

.github/workflows/release.yml

try to fix release CI

---

.github/workflows/release.yml

chore: try to fix CI for release

---

.github/workflows/release.yml

chore: add extra dep for arm mac CI

---

.github/workflows/release.yml

Try to fix CI

---

.github/workflows/release.yml

Fix CI (maybe)

---

Dockerfile.arm64
Dockerfile.armv7

chore: increase tauri cli ver for cross compilation dockerfiles

---

.github/workflows/release.yml

strip down CI for testing

---

components/kanban/Card.vue
components/kanban/Column.vue
components/modal/EditCard.vue

1. [x] Did you lint your code locally before submission?
2. [x] Did you test your feature thoroughly to ensure there are no bugs?

Add card duplication context menu

---

.github/workflows/release.yml

fix: correct dependency installation for ubuntu

---

Dockerfile.arm64
Dockerfile.armv7

chore: bump tauri cli version number

---

components/kanban/Column.vue
components/kanban/SearchBar.vue

feat: add search filtering with prefix support

---

.github/workflows/release.yml

fix: add missing frontend build part to CI

---

src-tauri/tauri.conf.json

fix: add font CSP to allow tag input x icon to render

---

i18n/locales/tr.json
i18n/locales/tr.json.license
nuxt.config.ts

This pull request adds full Turkish language localization support to Kanri by translating all UI elements, messages, and tooltips into Turkish.
- Translated all general UI actions and buttons
- Translated error messages and import/export functionality text
- Added translations for all modal dialogs, warnings, and confirmations
- Localized the homepage content, kanban board interface, and settings panels
This addition will make Kanri accessible to Turkish-speaking users, expanding the application's reach to a new language community. Turkey has a growing tech community that can benefit from using Kanri in their native language.
The translation has been tested with the Turkish language setting to ensure proper display of all text elements and correct grammar usage.

Add Turkish (tr) localization support

---

src-tauri/tauri.conf.json

fix: also bump version in tauri conf

---

components/LanguageSelector.vue
i18n/i18n.config.ts

Add i18n fixes to v0.8.2 release

---

components/LanguageSelector.vue
layouts/default.vue
nuxt.config.ts

fix: manually save language in tauri store and set manually on startup
